spring.application.name=servicio-reservas
server.port=8083

# ---------- Base de datos: reservas_db (PostgreSQL) ----------
spring.datasource.url=jdbc:postgresql://localhost:5433/reservas_db
spring.datasource.username=postgres
spring.datasource.password=postgreswasa123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ---------- Integracion SOA: las llamadas inter-servicio salen por el bus ESB ----------
services.gateway-url=http://localhost:8080

# ---------- JWT (Resource Server) ----------
# DEBE ser EXACTAMENTE el mismo valor que en Usuarios y Pagos para validar la firma.
security.jwt.secret=${JWT_SECRET:cambia-esta-clave-super-secreta-circuito-soa-2026-min-32-bytes-hs256}

# ---------- Quartz Scheduler ----------
# Usa JDBC (las tablas QRTZ_ viven en reservas_db).
spring.quartz.job-store-type=jdbc
# NO dejamos que Spring cree las tablas: se crean a mano con sql/quartz_tables_postgres.sql
spring.quartz.jdbc.initialize-schema=never
# Delegado especifico de PostgreSQL (maneja BYTEA correctamente)
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
# Prefijo de las tablas (coincide con el script SQL)
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
# Pool de hilos de Quartz
spring.quartz.properties.org.quartz.threadPool.threadCount=10

# ---------- Subida de archivos ----------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ---------- Observabilidad (Spring Boot Actuator + Prometheus) ----------
# Exponemos por HTTP solo health, info y prometheus (las metricas que scrapea Prometheus).
management.endpoints.web.exposure.include=health,info,prometheus
# Mostramos el detalle del health (estado de DB, disco, etc.).
management.endpoint.health.show-details=always
